# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    env:
      working-directory: ./presentation
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Markup Link Checker (mlc)
        uses: becheran/mlc@v0.14.0
        with:
          args: -d          
  test-and-release:
    runs-on: ubuntu-latest
    needs: [check-links]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      
      - name: Test
        run: go test ./...
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
